parameters:
    oro_dpd.order.attachment.comment.message.id: 'oro.dpd.order.attachment.comment.message.id'

services:
    oro_dpd.order.attachment.factory:
        class: 'Oro\Bundle\DPDBundle\Order\Shipping\Attachment\Factory\Basic\BasicAttachmentFromDPDTransactionFactory'
        public: true
        arguments:
            - '@oro_dpd.order.attachment.comment.provider'

    oro_dpd.order.attachment.comment.provider:
        class: 'Oro\Bundle\DPDBundle\Order\Shipping\Attachment\Comment\Provider\Basic\BasicOrderShippingAttachmentCommentProvider'
        arguments:
            - '%oro_dpd.order.attachment.comment.message.id%'
            - '@translator'
